In [26]:
import pandas as pd
designer_info_df = pd.read_parquet("data/final_info_designers.parquet")
designer_info_df

,designer_name,place_of_birth,year_birth,education,nationality,employer,locationSchoolLabel,countrySchoolLabel
0,Aage Thaarup,Copenhagen,1906.0,None,Denmark,[],None,None
1,Achille Maramotti,Reggio Emilia,1927.0,Sapienza University of Rome,Italy,[Max Mara],Gaeta,Italy
2,Achille Maramotti,Reggio Emilia,1927.0,Sapienza University of Rome,Italy,[Max Mara],Guidonia Montecelio,Italy
3,Achille Maramotti,Reggio Emilia,1927.0,Sapienza University of Rome,Italy,[Max Mara],Isernia,Italy
4,Achille Maramotti,Reggio Emilia,1927.0,Sapienza University of Rome,Italy,[Max Mara],Pomezia,Italy
...,...,...,...,...,...,...,...,...
5016,Zoe Latta,None,NaN,Rhode Island School of Design,None,None,Providence,United States
5017,Zoe Latta,None,NaN,Rhode Island School of Design,None,None,Providence,United States
5018,Zoe Latta,None,NaN,Rhode Island School of Design,None,None,Providence,United States
5019,Zowie Broach,None,NaN,None,None,None,None,None
5020,Zuhair Murad,Ras Baalbek,1971.0,None,Lebanon,None,None,None

In [12]:

df_school = pd.read_csv("data/names/school_names_designers_wikidata.csv")
df_school = df_school.dropna()
df_school = df_school.rename(columns= {"schoolLabel":"education"})
designer_info_df = designer_info_df.merge(df_school, how = "left")

In [27]:

designer_info_df = designer_info_df.drop_duplicates(subset= ['designer_name', 'place_of_birth', 'year_birth', 'education',
       'nationality',  'locationSchoolLabel', 'countrySchoolLabel'], ignore_index=True)

In [28]:
designer_info_df

,designer_name,place_of_birth,year_birth,education,nationality,employer,locationSchoolLabel,countrySchoolLabel
0,Aage Thaarup,Copenhagen,1906.0,None,Denmark,[],None,None
1,Achille Maramotti,Reggio Emilia,1927.0,Sapienza University of Rome,Italy,[Max Mara],Gaeta,Italy
2,Achille Maramotti,Reggio Emilia,1927.0,Sapienza University of Rome,Italy,[Max Mara],Guidonia Montecelio,Italy
3,Achille Maramotti,Reggio Emilia,1927.0,Sapienza University of Rome,Italy,[Max Mara],Isernia,Italy
4,Achille Maramotti,Reggio Emilia,1927.0,Sapienza University of Rome,Italy,[Max Mara],Pomezia,Italy
...,...,...,...,...,...,...,...,...
797,Zandra Rhodes,Chatham,1940.0,University for the Creative Arts,United Kingdom,None,None,None
798,Zandra Rhodes,Kent,1961.0,None,United Kingdom,[],None,None
799,Zoe Latta,None,NaN,Rhode Island School of Design,None,None,Providence,United States
800,Zowie Broach,None,NaN,None,None,None,None,None
801,Zuhair Murad,Ras Baalbek,1971.0,None,Lebanon,None,None,None

In [29]:
designer_info_df.to_parquet("data/final_info_designers.parquet")